FROM quay.io/signalfuse/collectd:latest

# Disable everything we can except elasticsearch
ENV COLLECTD_INTERVAL=3 COLLECTD_HOSTNAME=spark-test DISABLE_AGGREGATION=true DISABLE_CPU=true DISABLE_CPUFREQ=true DISABLE_DF=true DISABLE_DISK=true DISABLE_DOCKER=true DISABLE_HOST_MONITORING=true DISABLE_INTERFACE=true DISABLE_LOAD=true DISABLE_MEMORY=true DISABLE_PROTOCOLS=true DISABLE_VMEM=true DISABLE_UPTIME=true

# Debian is super minimalistic
RUN apt-get update &&\
    apt-get install -yq netcat curl

CMD /.docker/setup_spark

ADD integration-test/setup_spark /.docker/setup_spark

## The context of the image build should be the root dir of this repo!!
ADD spark_plugin.py /opt/collectd-spark/
ADD metrics.py /opt/collectd-spark/
ADD integration-test/20-spark-test.conf /etc/collectd/managed_config/
