#!/bin/bash

wait_for () {
    host=$1
    while ! nc -z $host 8080
    do
      echo "Didn't receive host 8080"
    done
}

for host in master
do
  wait_for $host
done
echo "FINISHED WAITING"
exec /.docker/run.sh
